package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, START, CREATE, RESULT, FRACTAL_RESULT, NEW_JOB_ADDED, JOB_STARTED, QUIT, STATUS
}
